# Pain intensity (continuous measure)

```{r}
# set pain_int direction
dir_pain_int <-
  outcome_key %>% 
  filter(outcome == "pain_int") %>% 
  pull(direction_of_improvement)

```


```{r}
mod_dat %>% 
  filter(str_detect(outcome, "pain_int"),
         type != "placebo", timepoint != "baseline") %>% 
  group_by(outcome_label, type_label, timepoint_label) %>% 
  summarise(
    n_studies = n_distinct(study),
    n_obs = length(study),
    Participants = sum(n)
  ) %>% 
  filter(Participants >= 200) %>% 
  ungroup() %>% 
  gt(
    groupname_col = "type_label"
  ) %>% 
  tab_header("Number of studies and arms") %>% 
  cols_label(
    outcome_label = "Outcome",
    n_studies = "Studies",
    n_obs = "Arms",
    type_label = "Comparison",
    timepoint_label = "Timepoint"
  ) %>% 
  tab_source_note("Comparisons with less than 200 participants excluded") %>% 
  tab_options(
    row_group.background.color = hpp_pal(1)
  )


```

## Summary of findings: post-intervention 

```{r}
nma_pi <- read_rds("exports/pain_int/nma-pi.rds")


```

```{r}
this_mod <- tar_read(nma_mod_dev)

sof_results <- sof_results_dat(this_mod)

this_int <- sof_results %>%
  pull(intervention) %>%
  paste(collapse = "; ") %>%
  str_to_sentence()

```

```{r}
meta <-
  sof_meta_tab(this_mod, this_int) %>%
  # eventually move to function
  t() %>%
  as_tibble(rownames = "category") %>%
  rename(
    desc = V1
  ) %>%
  mutate(across(everything(), str_to_sentence))



```



### PICO

```{r}
  meta %>% 
  kable() %>% 
  kable_styling(
    full_width = F,
    font_size = 6
  ) %>% 
  column_spec(2, 
           width = "4cm")

```






## Antidepressant NMA

```{r eval=FALSE}
nma_pain_int <- 
get_nma_dat(
  mod_dat,
  outcome == "pain_int",
  timepoint == "post_int",
  type %in% c("ad", "placebo")
) %>% 
  hpp_nma()

write_rds(nma_pain_int, "exports/pain_int/nma-pi.rds")

```



```{r}
read_rds("exports/pain_int/nma-pi.rds") %>%  
hpp_forest(mod_type = "lor", dir = dir_pain_int) +
coord_cartesian(xlim = c(-1, 5)) +
  labs(
    title = "Pain intensity and antidepressants",
    subtitle = "Post-intervention network meta-anlysis"
  )

```



```{r eval=FALSE}
nma_pain_int_cs <- 
get_nma_dat(
  mod_dat,
  outcome == "pain_int",
  timepoint == "change_score",
  type %in% c("ad", "placebo")
) %>% 
  hpp_nma()

write_rds(nma_pain_int_cs, "exports/pain_int/nma-cs.rds")

```



```{r}
read_rds("exports/pain_int/nma-cs.rds") %>%  
hpp_forest(mod_type = "lor", dir = dir_pain_int) +
coord_cartesian(xlim = c(-1, 5)) +
  labs(
    title = "Pain intensity and antidepressants",
    subtitle = "Change score network meta-anlysis"
  )

```

### Direct evidence

```{r}


```




***


```{r }
this_key_row <- 
subgroup_type %>% 
  filter(
    outcome == "pain_int",
    timepoint == "change_score",
    type == "ad"
  )

```


```{r eval=FALSE}
nma_pain_int_cs <- 
  pres_nma(this_key_row)

write_pres_nma(nma_pain_int_cs, this_key_row)

```

```{r}
nma_pain_int_cs <- read_rds("/home/cantabile/Documents/gh-repos/adpain/data/pres/subgroup_type_pain_int_ad_change_score_.rds")

```

```{r}
nma_pain_int_cs_plot <- make_forest(nma_pain_int_cs, this_key_row) 

```


```{r}
nma_pain_int_cs_plot + 
  facet_grid(class ~ ., scales = "free", space = "free") +
  coord_cartesian(xlim = c(-4, 1))

```

***

```{r }
this_key_row <- 
subgroup_type %>% 
  filter(
    outcome == "pain_int",
    timepoint == "post_int",
    type == "ad"
  )

```


```{r eval=FALSE}
nma_pain_int <- 
  pres_nma(this_key_row)

write_pres_nma(nma_pain_int, this_key_row)

```

```{r}
nma_pain_int <- read_rds("/home/cantabile/Documents/gh-repos/adpain/data/pres/subgroup_type_pain_int_ad_post_int_.rds")

```

```{r}
nma_pain_int_plot <- make_forest(nma_pain_int, this_key_row) 

```


```{r}
nma_pain_int_plot + 
  facet_grid(class ~ ., scales = "free", space = "free") +
  coord_cartesian(xlim = c(-4, 1))

```

## Pain intensity & SNRI

***

```{r}
this_key_row <- 
subgroup_type %>% 
  filter(
    outcome == "pain_int",
    timepoint == "post_int",
    type == "ad"
  )

make_forest(nma_pain_int, this_key_row, this_class = "snri")

```

***

```{r}
this_key_row <- 
subgroup_type %>% 
  filter(
    outcome == "pain_int",
    timepoint == "change_score",
    type == "ad"
  )

make_forest(nma_pain_int_cs, this_key_row, this_class = "snri")

```

## Direct evidence for SNRI in pain intensity

```{r}
this_pw <-

pw_results %>% 
  filter(subgroup == "subgroup_class",
         outcome == "pain_int",
         class == "snri",
         type == "ad"
         ) %>% 
  arrange(int_2, desc(participants), desc(n_studies)) 

this_pw %>% 
  select(timepoint, comp, n_studies, participants, int_2) %>% 
  rename_with(str_to_sentence, everything()) %>% 
  gt(groupname_col = "Int_2") %>% 
  tab_header("Pairwise comparisons of substantial pain by dose") %>% 
  cols_label(
    N_studies = "Studies",
    Comp = "Comparison"
  ) %>% 
  tab_options(row_group.background.color = hpp_pal(1)
    
  )

```

***

```{r}
this_pw %>% 
  filter(str_detect(comp, "dulox"), timepoint == "change_score") %>% 
  pull(pw_forest_file) %>% 
  read_rds()
  
```


***

```{r}
this_pw %>% 
  filter(str_detect(comp, "dulox"), timepoint == "post_int") %>% 
  pull(pw_forest_file) %>% 
  read_rds()
  
```


***

```{r}
this_pw %>% 
  filter(str_detect(comp, "miln"), timepoint == "change_score") %>% 
  pull(pw_forest_file) %>% 
  read_rds()
  
```


***

```{r}
this_pw %>% 
  filter(str_detect(comp, "miln"), timepoint == "post_int") %>% 
  pull(pw_forest_file) %>% 
  read_rds()
  
```

## SSRI & pain intensity

***

```{r}
this_key_row <- 
subgroup_type %>% 
  filter(
    outcome == "pain_int",
    timepoint == "change_score",
    type == "ad"
  )

make_forest(nma_pain_int_cs, this_key_row, this_class = "ssri")

```

***

```{r}
this_key_row <- 
subgroup_type %>% 
  filter(
    outcome == "pain_int",
    timepoint == "post_int",
    type == "ad"
  )

make_forest(nma_pain_int, this_key_row, this_class = "ssri")

```

## No direct evidence for SSRI in pain intensity

***

## Pain intensity and TCA

***

```{r}
this_key_row <- 
subgroup_type %>% 
  filter(
    outcome == "pain_int",
    timepoint == "change_score",
    type == "ad"
  )

make_forest(nma_pain_int_cs, this_key_row, this_class = "tca")

```

***

```{r}
this_key_row <- 
subgroup_type %>% 
  filter(
    outcome == "pain_int",
    timepoint == "post_int",
    type == "ad"
  )

make_forest(nma_pain_int, this_key_row, this_class = "tca")

```

## Pain intensity | Only direct evidence for amitriptyline

```{r}
this_pw <-
pw_results %>% 
  filter(subgroup == "subgroup_class",
         outcome == "pain_int",
         class == "tca",
         type == "ad"
         ) %>% 
  arrange(int_2, desc(participants), desc(n_studies)) 

this_pw %>% 
  select(timepoint, comp, n_studies, participants, int_2) %>% 
  rename_with(str_to_sentence, everything()) %>% 
  gt(groupname_col = "Int_2") %>% 
  tab_header("Pairwise comparisons of substantial pain by dose") %>% 
  cols_label(
    N_studies = "Studies",
    Comp = "Comparison"
  ) %>% 
  tab_options(row_group.background.color = hpp_pal(1)
    
  )

```

***

```{r}
this_pw$pw_forest_file %>% read_rds()
```
