# Adverse events

```{r}
adverse_dir <- 
  outcome_key %>% 
  filter(outcome == "adverse") %>% 
  pull(direction_of_improvement)
  
  
```


There are three types of adverse outcome. 

```{r}
mod_dat %>% 
  filter(str_detect(outcome, "adverse")) %>% 
  group_by(outcome_label) %>% 
  summarise(
    n_studies = n_distinct(study),
    n_obs = length(study),
    Participants = sum(n)
  ) %>% 
  gt() %>% 
  tab_header("Number of studies and arms") %>% 
  cols_label(
    outcome_label = "Outcome",
    n_studies = "Studies",
    n_obs = "Arms"
  ) %>% 
  tab_source_note("Comparisons with less than 200 participants excluded")


```


```{r }
adverse_comp <- 
  mod_dat %>% 
  filter(str_detect(outcome, "adverse")) %>% 
  group_by(outcome, type, timepoint) %>%  
  filter(type != "placebo") %>% 
  summarise(
    n_studies = n_distinct(study),
    n_obs = length(study),
    Participants = sum(n)
  ) %>% 
  filter(n_studies > 1)


```

***

```{r}
adverse_comp %>%
  ungroup() %>% 
  filter(Participants >= 200) %>% 
  gt(groupname_col = "outcome") %>%
  tab_header("Possible adverse comparisons") %>% 
  tab_options(row_group.background.color = hpp_pal(1))
```



## Adverse events

```{r eval=FALSE}
nma_adverse <- 
get_nma_dat(
  mod_dat,
  outcome == "adverse",
  timepoint == "post_int",
  type %in% c("ad", "placebo")
) %>% 
  hpp_nma()

write_rds(nma_adverse, "exports/adverse/nma-adverse.rds")
```

```{r}
nma_adverse <- read_rds("exports/adverse/nma-adverse.rds")

```

```{r}
hpp_forest(nma_adverse, mod_type = "lor", dir = "lower") +
  coord_cartesian(xlim = c(0, 5))

```

### Direct evidence for adverse events

```{r}
adverse_pw <- 
  pw_int(
    mod_dat,
    this_outcome = "adverse",
    this_type = "ad",
    this_timepoint = "post_int"
  ) 

```

```{r}
  adverse_pw %>% 
  filter(intervention == "duloxetine") %>%
  pull(mod) %>% 
  pluck(1, "rma_mv") %>% 
  pw_forest_plot(
    m_type = "lor",
    dir = adverse_dir
  ) +
  coord_cartesian(xlim = c(0, 1)) +
  labs(
    title = "Adverse events and duloxetine",
    subtitle = "Post-intervention antidepressant meta-analysis"
  )
  
```

```{r}
  adverse_pw %>% 
  filter(intervention == "amitriptyline") %>%
  pull(mod) %>% 
  pluck(1, "rma_mv") %>% 
  pw_forest_plot(
    m_type = "lor",
    dir = adverse_dir
  ) +
  coord_cartesian(xlim = c(0, 1)) +
  labs(
    title = "Adverse events and amitriptyline",
    subtitle = "Post-intervention antidepressant meta-analysis"
  )
  
```


```{r}
  adverse_pw %>% 
  filter(intervention == "milnacipran") %>%
  pull(mod) %>% 
  pluck(1, "rma_mv") %>% 
  pw_forest_plot(
    m_type = "lor",
    dir = adverse_dir
  ) +
    labs(
    title = "Adverse events and milnacipran",
    subtitle = "Post-intervention antidepressant meta-analysis"
  )

```



## Serious adverse events

```{r eval=FALSE}
nma_adverse_serious <- 
get_nma_dat(
  mod_dat,
  outcome == "serious_adverse",
  timepoint == "post_int",
  type %in% c("ad", "placebo")
) %>% 
  hpp_nma()

write_rds(
  nma_adverse_serious,
  "exports/adverse/nma-serious.rds")

```



```{r}
read_rds("exports/adverse/nma-serious.rds") %>% 
  hpp_forest(mod_type = "lor", dir = "lower") +
  coord_cartesian(xlim = c(0, 5))


```


### Duloxetine

```{r}
get_pw_dat(
  dat = mod_dat,
  outcome = "serious_adverse",
  type = "ad",
  timepoint = "post_int",
  g1 = "duloxetine",
  g2 = "placebo"
) %>% 
  mutate(
    model_type = if_else(
      is.na(model_type),
      "lor",
      model_type
    ) 
  ) %>% 
  hpp_rma() %>% 
  pw_forest_plot(
  m_type = "lor",
  dir = adverse_dir
)

```



## Dropout due to adverse events

```{r eval=FALSE}
nma_adverse_dropout <- 
get_nma_dat(
  mod_dat,
  outcome == "adverse_dropout",
  timepoint == "post_int",
  type %in% c("ad", "placebo")
) %>% 
  hpp_nma()

write_rds(
  nma_adverse_dropout,
  "exports/adverse/nma-dropout.rds"
)

```


```{r}
nma_dropout <- read_rds("exports/adverse/nma-dropout.rds")

hpp_forest(nma_dropout, mod_type = "lor", dir = "lower") +
  coord_cartesian(
    xlim = c(0, 10)
  )

```


