---
title: "Antidepressants for pain management in adults with chronic pain"
description: |
  Network meta-analysis results
site: bookdown::bookdown_site
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warnings = FALSE, message = FALSE)

knitr::opts_knit$set(root.dir = "../")

suppressPackageStartupMessages({
  library(tidyverse)
  library(multinma)
  library(targets)
  library(assertthat)
  library(glue)
  library(gt)
})

source("preamble.R")

```


# Overview

```{r make summary data}

summary_dat <- obs_dat %>% 
  filter(timepoint != "baseline")

```



## Observations included

```{r observations tab}
summary_dat %>%
  filter(timepoint != "baseline") %>% 
  group_by(outcome_label, intervention_grouping) %>% 
  summarise(
    studies = n_distinct(study_id),
    n_interventions = n_distinct(intervention),
    interventions = unique(intervention) %>% paste(collapse = ", "),
    n_conditions = n_distinct(general_pain_grouping),
    conditions = unique(general_pain_grouping) %>% paste(collapse = ", "),
    timepoint = unique(timepoint) %>% paste(collapse = ", "),
    change_score = sum(change_score, na.rm = TRUE),
    participants = sum(n, na.rm = TRUE)
  ) %>% 
  arrange(outcome_label, desc(participants), desc(studies)) %>% 
  gt() %>% 
  tab_header(
    "Outcome summary of interventions, studies, and conditions"
  ) %>% 
  tab_source_note("General pain grouping is currently being used, but this can be switched or duplicated for IASP.") %>% 
  tab_options(
    table.font.size = 12,
    row_group.background.color = hpp_pal(1),
    table.layout = "auto"
  )

```

## Summary by condition

```{r condition tab}

summary_dat %>% 
  group_by(
    outcome_label, general_pain_grouping, time_no_change
  ) %>% 
  summarise(
    studies = n_distinct(study_id),
    participants = sum(n, na.rm = TRUE),
    interventions = unique(intervention) %>% paste(collapse = ";")
  ) %>% 
  ungroup() %>% 
  group_by(outcome_label) %>% 
  arrange(outcome_label, desc(participants), desc(studies)) %>% 
  gt() %>% 
  tab_options(
    table.font.size = 12,
    row_group.background.color = hpp_pal(1)
  )
  


```

## Summary by class


```{r class tab}

summary_dat %>% 
  group_by(
    outcome_label, time_no_change, ad_class
  ) %>% 
  filter(
    !is.na(ad_class),
    ad_class != "n/a"
  ) %>% 
  summarise(
    studies = n_distinct(study_id),
    participants = sum(n, na.rm = TRUE),
    interventions = unique(intervention) %>% paste(collapse = ";")
  ) %>% 
  ungroup() %>% 
  group_by(outcome_label) %>% 
  arrange(outcome_label, desc(participants), desc(studies)) %>% 
  gt() %>% 
  tab_options(
    table.font.size = 12,
    row_group.background.color = hpp_pal(1)
  )
  


```

## Summmary by intervention

```{r intervention tab}
summary_dat %>% 
  filter(
    intervention_grouping == "antidepressant"
  ) %>% 
  group_by(outcome_label, intervention) %>% 
  summarise(
    studies = n_distinct(study_id),
    participants = sum(n, na.rm = TRUE)
  ) %>% 
  arrange(outcome_label, desc(participants)) %>%
  gt()  %>% 
  tab_options(
    table.font.size = 12,
    row_group.background.color = hpp_pal(1)
  )
  


```



## Comparisons

```{r pw comp tab, eval=FALSE, message=FALSE}
# fix later

tar_read(pw_type_group) %>%
  left_join(tar_read(r_outcome_key)) %>% 
  group_by(outcome_label, comp_grouping, interventions, timepoint) %>% 
  summarise(
    studies = n_distinct(study_id)
  ) %>% 
  arrange(outcome_label, desc(studies)) %>% 
  ungroup() %>%
  gt(groupname_col ="outcome") %>% 
  tab_header("Comparison groups used in pairwise models") %>% 
  tab_options(
    row_group.background.color = hpp_pal(1)
  )

```


